"""
Fetch harvest statistics from Idaho Fish & Game Harvest Finder.
Uses Playwright to drive the web UI and export CSV data.

Run: python -m playwright install chromium
"""
import asyncio
import csv
import json
from pathlib import Path
from playwright.async_api import async_playwright

OUTPUT_DIR = Path(__file__).parents[2] / "data" / "raw"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

HARVEST_FINDER_URL = (
    "https://fishandgame.idaho.gov/ifwis/huntplanner/harvestfinder.aspx"
)

SPECIES = [
    "Deer",
    "Elk",
    "Pronghorn",
    "Moose",
    "Bighorn Sheep",
    "Mountain Goat",
    "Black Bear",
    "Mountain Lion",
    "Gray Wolf",
]

YEARS = list(range(2000, 2025))


async def scrape_harvest(species: str, year: int) -> list[dict]:
    """Scrape harvest data for a single species/year combo."""
    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        page = await browser.new_page()
        await page.goto(HARVEST_FINDER_URL, wait_until="networkidle")

        # TODO: Map specific selectors after inspecting the live page
        # The Harvest Finder is an ASP.NET WebForms app — selectors will be
        # autogenerated IDs like ctl00_ContentPlaceHolder1_ddlSpecies
        # We'll capture the network response when CSV export is triggered.

        await browser.close()
        return []


async def capture_csv_export(species: str, year: int) -> Path | None:
    """
    Drive the Harvest Finder UI to select species/year and download CSV.
    Returns the path to the saved CSV, or None if it failed.
    """
    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        context = await browser.new_context(accept_downloads=True)
        page = await context.new_page()

        print(f"  Loading Harvest Finder for {species} {year}...")
        await page.goto(HARVEST_FINDER_URL, wait_until="networkidle")

        # Intercept CSV download
        async with page.expect_download() as download_info:
            # These selectors need verification against the live page
            # Run with headless=False first to inspect the UI
            try:
                await page.select_option('[id*="Species"]', label=species)
                await page.select_option('[id*="Year"]', str(year))
                await page.click('[id*="btnSearch"]')
                await page.wait_for_load_state("networkidle")
                await page.click('[id*="btnExportCSV"], [value*="CSV"], text=CSV')
            except Exception as e:
                print(f"  Selector error for {species} {year}: {e}")
                await browser.close()
                return None

        download = await download_info.value
        out_path = OUTPUT_DIR / f"harvest_{species.lower().replace(' ', '_')}_{year}.csv"
        await download.save_as(out_path)
        await browser.close()
        print(f"  Saved: {out_path}")
        return out_path


async def main(species_filter: list[str] | None = None, year_filter: list[int] | None = None):
    species_list = species_filter or SPECIES
    year_list = year_filter or YEARS

    print(f"Starting harvest scrape: {len(species_list)} species x {len(year_list)} years")

    results = []
    for species in species_list:
        for year in year_list:
            path = await capture_csv_export(species, year)
            results.append({"species": species, "year": year, "path": str(path)})

    summary_path = OUTPUT_DIR / "scrape_manifest.json"
    with open(summary_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nManifest saved: {summary_path}")


if __name__ == "__main__":
    # Quick test: just deer for last 3 years
    asyncio.run(main(species_filter=["Deer"], year_filter=[2022, 2023, 2024]))
